version: "3"
services:
  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
